### ISSUE TITLE
Clarify package restore page

### ISSUE THREAD

**Issue by ghost** [NuGet/NuGetDocs#115]
Please clarify on documentation page http://docs.nuget.org/docs/workflows/using-nuget-without-committing-packages which files have to go under sourcecontrol and which files a generated on build. 

 I think since recent versions of nuget it is not more necessary to check in nuget.exe. 
 It is re downloaded when missing.

**Comment by xavierdecoster** [comment]
The redesign added a new [Package Restore page](http://docs.nuget.org/Consume/Package-Restore)

Closing this issue, as the approach you describe using the automatic download of `nuget.exe` refers to the [MSBuild-integrated package restore](http://docs.nuget.org/Consume/Package-Restore#msbuild-integrated-package-restore), which has been outdated by the [newer automatic package restore](http://docs.nuget.org/Consume/Package-Restore#automatic-package-restore-in-visual-studio).
