### ISSUE TITLE
Package restore "PackageSources" documentation

### ISSUE THREAD

**Issue by robblovell** [NuGet/NuGetDocs#12]
I can't find anywhere that the proper use of this config item is demonstrated:

Here is the default:
<pre><code>
&lt;PackageSources&gt;""&lt;/PackageSources&gt;
</code></pre>

I tried to change this to what was normally in the nuget.config file:

<pre>
&lt;packageSources&gt;
&lt;add key="localrepo" value="c:\localrepo" /&gt;
&lt;add key="3rdparty" value="\\name\of\repo1" /&gt;
&lt;add key="repo" value="\\name\of\repo2\Trunk" /&gt;
&lt;add key="official" value="\\name\of\repo\official" /&gt;
&lt;/packageSources&gt;
</pre>
That would be what I would expect, but that didn't work.
So, I tried a number of other things: 
<pre>
"c:\localrepo,\\name\of\repo1,\\name\of\repo12"
</pre>
I tried:
<pre><code>
&lt;PackageSources&gt;"$(SolutionDir).nuget\NuGet.Config"&lt;/PackageSources&gt;
</code></pre>

I tried:
<pre><code>
&lt;PackageSources&gt;$(SolutionDir).nuget\NuGet.Config&lt;/PackageSources&gt;
</code></pre>
 It looks like it is passing a string directly to the nuget command, but the nuget command documentation doesn't show an example.

 It would be good to document this in the nuget command and package restore documentation.

**Comment by harikm86** [comment]
This is now documented. https://docs.nuget.org/consume/nuget-config-settings#package-sources
