### ISSUE TITLE
repositories.config use case and documentation

### ISSUE THREAD

**Issue by robblovell** [NuGet/NuGetDocs#13]
I am having trouble with repositories.config and I see no documentation on when, how, and why this appears in the packages.config directory.  A search in the documentation doesn't return results.  

The background is that we are using the package restore mechanism that has the location of the packages.config already in a configuration file, so there is no need for "repositories.config".    In my view the name "repositories.config" implies that this is the list of the package repositories, but in fact it points to package.config files which in actuality are dependency lists.  This is misleading.

Anyway....

Here is some more background via a complaint: (take this with a grain of salt on a platter of understanding, nuget solves a lot of problems, so I really would like for it to be robust and understandable.)

This is a real problem for us. First, where is the documentation on what this is? Second, it has completely screwed up our workflow by suddenly appearing when one of our packages is added as a reference. We expected that the package restore module would have no problem bringing in this package. We don't check in packages and we use package restore. The workflow is to NOT check in the packages directory. 

The work around I guess is to rename the package restore directory and check in the packages directory, but that doesn't solve the problem of why it's occurring in the first place? Package restore already knows the location of the packages.config in its configuration file and repositories.config is completely unnecessary. 

On another point, the name repositories.config implies that there is a repository there with nuget packages, not a list of dependencies. So the name itself doesn't imply why it's there.

So my question remains WHY? Where is the documentation? What is the use case for this?

**Comment by harikm86** [comment]
Closing stale issue.
