### ISSUE TITLE
Create a reference doc section for Package Restore and Team Build

### ISSUE THREAD

**Issue by jeffhandley** [NuGet/NuGetDocs#130]
With the new package restore features and documentation, customers are asking how to utilize the features alongside TFS Team Build.

We should add a section to http://docs.nuget.org/docs/reference/package-restore for Team Build, where we outline how to set up a build.proj for use by Team Build.

**Comment by terrajobst** [comment]
It's essentially documented [here](http://docs.nuget.org/consume/package-restore/team-build), right?

**Comment by jeffhandley** [comment]
Yep
