### ISSUE TITLE
Improper Highlighting in the codeblock in the versioning doc page under update package

### ISSUE THREAD

**Issue by joostdenijs** [NuGet/NuGetDocs#148]
In the update package part of the versioning documentation page: http://docs.nuget.org/docs/reference/versioning, the highlighting of different names denoted by ' tags surrounding (which show up green), is messed up on the last block by the Don't which uses the ' tag for a contraction.  This should not make the text color in this part look off.
![nuget text coloring issue](https://f.cloud.github.com/assets/1128742/1478800/040f0a94-4673-11e3-80f3-5e6b5aab17b2.PNG)

**Comment by xavierdecoster** [comment]
fixed in redesign
