### ISSUE TITLE
NuGet Package Manager in VS2013 (won't uninstall)

### ISSUE THREAD

**Issue by DrYSG** [NuGet/NuGetDocs#176]
I have VS2013 (12.0.30110.00) Update 1 on a Win7 64 bit box.

I want to install the latest version of the NuGet Package manager (I have version. 2.7.411011.371) It is now up to version 2.8.  The automatic update fails,

and when I do an UNINSTALL from the Extensions and Updates (it says it works, but when I reboot VS2013) it is still there.

Ideas?

-------

Microsoft Visual Studio Professional 2013
Version 12.0.30110.00 Update 1
Microsoft .NET Framework
Version 4.5.50938

Installed Version: Professional

LightSwitch for Visual Studio 2013   06177-004-0446016-02552
Microsoft LightSwitch for Visual Studio 2013

Microsoft Office Developer Tools for Visual Studio 2013 ENU   06177-004-0446016-02552
Microsoft Office Developer Tools for Visual Studio 2013 ENU

Team Explorer for Visual Studio 2013   06177-004-0446016-02552
Microsoft Team Explorer for Visual Studio 2013

Visual Basic 2013   06177-004-0446016-02552
Microsoft Visual Basic 2013

Visual C# 2013   06177-004-0446016-02552
Microsoft Visual C# 2013

Visual C++ 2013   06177-004-0446016-02552
Microsoft Visual C++ 2013

Visual F# 2013   06177-004-0446016-02552
Microsoft Visual F# 2013

Visual Studio 2013 Code Analysis Spell Checker   06177-004-0446016-02552
Microsoft® Visual Studio® 2013 Code Analysis Spell Checker

Portions of International CorrectSpell™ spelling correction system © 1993 by Lernout & Hauspie Speech Products N.V. All rights reserved.

The American Heritage® Dictionary of the English Language, Third Edition Copyright © 1992 Houghton Mifflin Company. Electronic version licensed from Lernout & Hauspie Speech Products N.V. All rights reserved.

AnkhSVN - Subversion Support for Visual Studio   2.5.12266.473
AnkhSVN - Subversion Support for Visual Studio 2.5.12266.473 
 * Ankh.Package 2.5.12266.473
 * Subversion 1.8.4 via SharpSvn 1.8004.2605.15365

SharpSvn is linked to: Apr 1.4.8, Apr-util 1.5.2, Cyrus Sasl 2.1.23, OpenSSL 1.0.1e 11 Feb 2013, serf 1.3.2, SQLite 3.7.17, Subversion 1.8.4-SharpSvn-1.8.4, ZLib 1.2.8
SharpSvn is optionally linked to: Berkeley DB 4.4.20, SharpPlink 1.8004.2605.15365

ASP.NET and Web Tools   2013.1.41009
Microsoft Web Developer Tools contains the following components:
Support for creating and opening ASP.NET web projects
Browser Link: A communication channel between Visual Studio and browsers
Editor extensions for HTML, CSS, and JavaScript
Page Inspector: Inspection tool for ASP.NET web projects
Scaffolding: A framework for building and running code generators
Server Explorer extensions for Windows Azure Web Sites
Web publishing: Extensions for publishing ASP.NET web projects to hosting providers, on-premises servers, or Windows Azure

ASP.NET Web Frameworks and Tools 2012.2   4.1.21001.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.0.11213.0
For additional information, visit http://www.asp.net/

CodeMaid   #114
CodeMaid is an open source Visual Studio extension to cleanup, dig through and simplify our C#, C++, F#, VB, XAML, XML, ASP, HTML, CSS, LESS, JavaScript and TypeScript coding.

Written by Steve Cadwallader, for more information visit http://www.codemaid.net/

Common Azure Tools   1.0
Provides common services for use by Azure Mobile Services and Windows Azure Tools.

Node.js Tools   1.0.11119.03
Adds support for developing and debugging Node.js apps in Visual Studio

Node.js Tools - Profiling   1.0.11119.03
Profiling support for Node.js projects.

NuGet Package Manager   2.7.41101.371
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   12.0.30919.1
Microsoft SQL Server Data Tools

Visual Studio 12 Editor Extension   1.0
Information about my package

Windows Azure Mobile Services Tools   1.0
Windows Azure Mobile Services Tools

Windows Azure Remote Debugging   1.0
Windows Azure Remote Debugging Community Technology Preview

Windows Azure Tools   2.2
Windows Azure Tools for Microsoft Visual Studio 2013 - v2.2.11003.1601

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

**Comment by harikm86** [comment]
Not a docs issues refer to the previous comment
