### ISSUE TITLE
Doc Refresh - Installing NuGet

### ISSUE THREAD

**Issue by joostdenijs** [NuGet/NuGetDocs#199]
- [ ] Way too many steps.  It's easy, make the docs easy.
 - [ ] NuGet Command Line installation could fit better as a part of Creating Packages workflow
 - [ ] After simplifying, it might be easier to have the article be Downloading and Updating the NuGet Client

**Comment by harikm86** [comment]
https://github.com/NuGet/NuGetDocs/issues/467
