### ISSUE TITLE
Package restore "PackageSources" documentation

### ISSUE THREAD

**Issue by howarddierking** [NuGet/NuGetDocs#20]
from http://nuget.codeplex.com/workitem/1820

Description
I can't find anywhere that the proper use of this config item is demonstrated:

```xml
<PackageSources>""</PackageSources>
```

I tried:

```xml
<packageSources>
<add key="localrepo" value="c:\localrepo" />
<add key="3rdparty" value="\\name\of\repo1" />
<add key="repo" value="\\name\of\repo2\Trunk" />
<add key="official" value="\\name\of\repo\official" />
</packageSources>
```

But it looks like it is passing a string directly to the nuget command, but the nuget command documentation doesn't show an example. Comma separated list? XML as a string? what? I will try:

"c:\localrepo,\\name\of\repo1,\\name\of\repo12"

Which may work, but it would be good to document this in the nuget command and package restore documentation.

File Attachments
No files are attached

Comments
robblovell wrote Jan 4 at 11:27 AM [x]
thanks, that works.

pranavkm wrote Jan 4 at 10:38 AM [x]
It should be a semi-colon separated. NuGet.exe mimics msbuild.exe's behavior when it comes to argument separators.

robblovell wrote Jan 4 at 10:30 AM [x]
This is definitely broken if all of the below attempts didn't work, nothing else would make sense unless the semantics of what this is supposed to do is different than what is in the nuget.config file. Perhaps it only works for one repo?

robblovell wrote Jan 4 at 10:21 AM [x]
This doesn't work either:
<PackageSources>"$(SolutionDir).nuget\NuGet.Config"</PackageSources>

Nor this:
<PackageSources>$(SolutionDir).nuget\NuGet.Config</PackageSources>

robblovell wrote Jan 4 at 9:54 AM [x]
will do.

robblovell wrote Jan 4 at 9:54 AM [x]
comma separated doesn't work either.

pranavkm wrote Jan 4 at 9:16 AM [x]
Could you send a pull request to the docs site? http://docs.nuget.org/docs/Contribute/Contributing-to-NuGet-Documentation#Making_a_change_to_existing_documentation

**Comment by harikm86** [comment]
https://docs.nuget.org/consume/nuget-config-settings. Fixed
