### ISSUE TITLE
Doc Refresh - Creating and Publishing a Package

### ISSUE THREAD

**Issue by joostdenijs** [NuGet/NuGetDocs#204]
- [ ] Structure of the Article is confusing
 - [ ] Short summary at the start to go over what is covered would be useful
 - [ ] Instead of each possible 200 level feature being appended to the end of the 100 level instructions.  It may be useful to have seperate 200 level articles for each of those.
 - [ ] From the title of the article I would expect to have the 100 level workflow of creating a NuGet package (from project or assembly), modify the metadata, and then upload.  Anything beyond that should be in either reference supplements or 200 level walk-throughs.
 - [ ] Make it clear for each code snippet which file/tool is being shown.

**Comment by harikm86** [comment]
https://github.com/NuGet/NuGetDocs/issues/467
