### ISSUE TITLE
Reference docs for target property of files element could be clearer

### ISSUE THREAD

**Issue by jeffhandley** [NuGet/NuGetDocs#25]
Migrated from: http://nuget.codeplex.com/workitem/2107

The Nuspec reference at http://docs.nuget.org/docs/reference/nuspec-reference explains the <target> attribute in the <files> element as:-

target	 This is a relative path to the directory within the package where the source files will be placed.

It would be helpful if it stated that the relative path should begin with one of 'lib', 'content' or 'tools'.

Without this guidance it's all too easy to create a target that isn't in the content folder and thus nothing happens when the package is installed.

**Comment by harikm86** [comment]
Fixed
