### ISSUE TITLE
Redirection link broken

### ISSUE THREAD

**Issue by bhuvak** [NuGet/NuGetDocs#266]
The redirection link in the first line in article http://docs.nuget.org/docs/contribute/setting-up-a-local-gallery seems to be broken.
It's redirecting to https://github.com/NuGet/NuGetGallery/blob/master/README.markdown where as the actual link is https://github.com/NuGet/NuGetGallery/blob/master/README.md ( .md instead of markdown)

**Comment by jeffhandley** [comment]
Also addressed with the site redesign
