### ISSUE TITLE
Invalid link in 'using the package manager console' page

### ISSUE THREAD

**Issue by jamesfancy** [NuGet/NuGetDocs#290]
http://docs.nuget.org/docs/start-here/using-the-package-manager-console

See the first paragraph

> This topic describes how to find, install, remove, and update NuGet packages using PowerShell commands. You can also work with packages using the Manage NuGet Packages dialog box. For more information, see \[Using the Manage NuGet Packages dialog\](Using-the Add-Library-Package-Reference-Dialog-Box).

I think `[Using the Manage NuGet Packages dialog](Using-the Add-Library-Package-Reference-Dialog-Box)` should be made a link. Maybe a `-` was missed between `Using-the` and `Add-Library-...`

However, the link should be `http://docs.nuget.org/docs/start-here/Managing-NuGet-Packages-Using-The-Dialog`

**Comment by jeffhandley** [comment]
Fixed with the site redesign
