### ISSUE TITLE
Broken link to release notes on home page

### ISSUE THREAD

**Issue by matatk** [NuGet/NuGetDocs#315]
When trying to follow the link to http://docs.nuget.org/docs/release-notes/nuget-2.8.3 that is presently on the home page, I got a 404.  I did find the release notes (by browsing through the site) and they're actually at http://docs.nuget.org/release-notes/nuget-2.8.3 (the '`/docs`' needs taking out).

The 404 message directed me here to report bugs; not 100% sure this is the place to report site bugs, though -- sorry if not.

**Comment by xavierdecoster** [comment]
The release notes link pointing to 2.8.3 seems to be working fine for me and does not include the `/docs/` part in the URL? Can you try clearing your cache and refreshing the page?
If it's still there, can you point me to the anchor in our github repository? (or would you mind sending a pull request?)

Thanks!

**Comment by matatk** [comment]
I'm not fully sure if the problem is in this repo (though the 404 page directed me here to report the issue), but if you go to https://www.nuget.org you'll see a heading there called "NuGet 2.8.3 Released" and it's the "release notes" link under there.  I've tried force-refreshing and a different browser, and I still get the broken link with '`/docs`' in it.

**Comment by xavierdecoster** [comment]
Ah, your request originates from the NuGetGallery home page :) Thx! will look into it.
