### ISSUE TITLE
Improve documentation for the $references$ replacement token

### ISSUE THREAD

**Issue by StevenLiekens** [NuGet/NuGetDocs#329]
The Nuspec Reference page describes the existence of a `$references$` replacement token, but the documentation is not very useful.

The Nuspec Reference should be updated to contain a sample that demonstrates the `$references$` token, and a description of what it replaces and how it is replaced.

http://docs.nuget.org/Create/Nuspec-Reference#replacement-tokens

**Comment by karann-msft** [comment]
This issue was moved to NuGet/Home#3366
