### ISSUE TITLE
No way to list packages in solution from commandline

### ISSUE THREAD

**Issue by opinionmachine** [NuGet/NuGetDocs#340]
In certain quality compliance scenarios you need to list all external dependencies to your product with a short description and a version number, Since this information arguably already exists within Nuget if you handle your dependencies through nuget, it would be prefereable to just let nuget list whatever you have in your solution and store that as a build artefact and not waste a single drop of sweat on producing yet another document that nobody will read. There is a simple powershell way of producing this output from nuget console:

    (@(Get-Project -All | ForEach-Object { Get-Package -ProjectName $_.ProjectName }) | Select-Object -Unique | Sort-Object)

But that can't be used anywhere outside of VS of course. 

Nuget commandline could come to the rescue here, but of course there is no documented way of just enumerating all nuget packages in a solution listing name/id, version and description 

I'm fine with either solution, making the Nuget Console PS cmdlet loadable from outsite VS or making nuget commandline usable in this context.

**Comment by maartenba** [comment]
This should give you a similar list when run in PowerShell from your solution folder:

    $packages = @{ }

    $packagesConfigs = Get-ChildItem -Filter packages.config -Recurse
    $packagesConfigs | %{
        $packagesConfig = Get-Content $_.FullName
        $packagesConfigXml = [xml]$packagesConfig
        $packagesConfigXml.packages.package | %{
            $packages[$_.id] = $_.version
        }
    }

    $packages.GetEnumerator() | Sort-Object Name

It's obviously not including the package description, but it's a start. Alternatively, you could use a similar approach from .NET code and use the `NuGet.Core` package to load the actual `.nupkg` files and list some metadata.
