### ISSUE TITLE
Mirror Command, Doc for Enabling Doesn't Work

### ISSUE THREAD

**Issue by tshadle** [NuGet/NuGetDocs#345]
In the NuGet Command Line Reference, for the Mirror Command, the doc states

> Note: to enable this command, navigate to http://build.nuget.org/ (there's a Guest log in option), copy NuGet.ServerExtensions.dll from Artifacts,CommandLine.ServerExtensions to your local disk in the same directory as NuGet.exe.

There are no artifacts available from that site to download as Guest. I cannot find any other instructions for enabling Mirror, or a note that it's been replaced or deprecated.

**Comment by maartenba** [comment]
This mirror is currently disabled until we have full v3.0 out. /cc @yishaigalatzer

**Comment by karann-msft** [comment]
This issue was moved to NuGet/Home#3365
