### ISSUE TITLE
Package restore doesn't download packages not referenced by a project

### ISSUE THREAD

**Issue by mbolesta** [NuGet/NuGetDocs#38]
One of our packages that our MSBUILD file uses is the NUnit.TestRunners package.  It's not referenced by any of our projects in the solution - just by the build.

Is there any way to get this to work with NuGet package restore?  I'd like to remove the packages folder from source control without manually having to install the NUnit.TestRunners package everywhere.

**Comment by jeffhandley** [comment]
This was addressed with NuGet's Automatic Package Restore.
