### ISSUE TITLE
Doc Request: Project.lock.json

### ISSUE THREAD

**Issue by harikmenon** [NuGet/NuGetDocs#470]
Some examples of the content we would like to see

1.	If project.json contains * and you want repeatable builds without checking in the lock file, you must lock down the sources used for restore so that you control the content.  This ensures that the * will always pick the same version.
2.	If project.json contains * and you want repeatable builds while checking in the lock file you can do so, but devs must be aware of this and know that whenever they change dependencies they need to update the lock file and check it in.
3.	If project.json does not contain *s then you should have repeatable builds so long as you have an exact-match to the versions you reference on one of your package sources and those packages remain immutable.

**Comment by karann-msft** [comment]
This issue was moved to NuGet/Home#3364
