### ISSUE TITLE
Consider using different color schema for code snippets and CLI commands

### ISSUE THREAD

**Issue by alpaix** [NuGet/NuGetDocs#519]
Current prototype intensively uses dark background for code snippets and command line samples. This can be confusing to some users especially when putting snippets close to VS dark screenshots

![image](https://cloud.githubusercontent.com/assets/8239356/17376813/02e2220a-596c-11e6-98e7-ab8bc2cdaa4d.png)

Consider setting white background for code as in [ASP.NET documentation](https://docs.asp.net/en/latest/getting-started.html).

![image](https://cloud.githubusercontent.com/assets/8239356/17376893/6bc04d42-596c-11e6-9668-c6f16069d80e.png)

**Comment by alpaix** [comment]
Apart from the background color as it treats all code blocks the same way it also does incorrect syntax highlighting for CLI lines:

![image](https://cloud.githubusercontent.com/assets/8239356/17379609/124eccdc-5978-11e6-9d9d-451ceb9869da.png)

So we should think of having different markups for regular code and CLI samples.

**Comment by karann-msft** [comment]
Will be fixed when we move to docs.microsoft.com
