### ISSUE TITLE
Add a copy button to code snippets

### ISSUE THREAD

**Issue by alpaix** [NuGet/NuGetDocs#530]
Add a copy button to code snippets.

**Comment by alpaix** [comment]
Considered two alternatives: [ZeroClipboard.js](http://zeroclipboard.org/) and [clipboard.js](https://clipboardjs.com/). Neither of them is perfect. First implements clipboard operations via hidden Flash component (it won't work if a user like me disabled Flash from running in a browser). Second works by calling `execComand` which is not supported in Safari.

After testing them both I'm leaning toward `clipboard.js` as it has no dependencies and has minimal footprint.

**Comment by karann-msft** [comment]
Done!
