### ISSUE TITLE
Extraneous spaces in Nuget 2.1 release notes

### ISSUE THREAD

**Issue by devuxer** [NuGet/NuGetDocs#57]
Please refer to this page:
http://docs.nuget.org/docs/release-notes/nuget-2.1

This snippet has extraneous spaces that will cause fail if you copy/paste this example:

    <configuration>
      <config>
        <add key=" repositoryPath" value=" C:\myteam\teampackages" />
      </config>
      ... 
    </configuration>

Should be:

        <add key="repositoryPath" value="C:\myteam\teampackages" />

I noticed the extra space before the path (because I had to change the path), but I failed to notice the extra space before "repositoryPath". After several failed attempts to get it to "take", I finally realized.

**Comment by jeffhandley** [comment]
This has been fixed
