### ISSUE TITLE
Update Latest 2.x links to 2.12

### ISSUE THREAD

**Issue by bbrandt** [NuGet/NuGetDocs#591]
These downloads still point to 2.8.6 as latest 2.x release.  Can these be updated to point to 2.12?  Is this something I can perform and submit a pull request for?

https://dist.nuget.org/index.html
https://docs.nuget.org/consume/installing-nuget

For anyone else tracking this, a workaround for downloading v2.12 of nuget.exe seems to be getting it from [NuGet](https://www.nuget.org/packages/NuGet.CommandLine/2.12.0):

1. Download from: https://www.nuget.org/api/v2/package/NuGet.CommandLine/2.12.0
2. Extract with 7zip
3. Get nuget.exe from the tools folder

**Comment by yishaigalatzer** [comment]
We did not release nor support a 2.12 version of nuget.exe as an official release, the package was released as part of the build, but we never intended to fully support or bug fix this version of nuget.exe.

If there is an issue with 3.4.4 that prevents you from using it, please let us know.

There is no way to PR a fix to dist.nuget.org, this is strictly an operational site we maintain.

Interested to hear why you are looking for a 2.12 nuget.exe as a released version, so we could potentially rethink our stance.

Thanks!

**Comment by bbrandt** [comment]
I made the assumption that since we are still on VS2013 and our IDE updated to NuGet 2.12, our build scripts had to update to using 2.12.  I am testing the scripts now with the latest 3.x release instead.

**Comment by bbrandt** [comment]
I've now updated our psake scripts to use latest NuGet v3 to perform restore, update, pack, and push.  Seems to all be working, besides NuGet/Home#2449 which we will workaround for now.  Thanks for the guidance!
